### ISSUE TITLE
CT dispose is not supported, exists for the lifetime of the sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#279]
```
vector-addition : fuzz : unbuilt : assertSlow
http://127.0.0.1/continuous-testing/ct-snapshots/1688588829341/vector-addition/vector-addition_en.html?continuousTest=%7B%22test%22%3A%5B%22vector-addition%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1688588829341%22%2C%22timestamp%22%3A1688592068894%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Error: Assertion failed: dispose is not supported, exists for the lifetime of the sim
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1688588829341/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1688588829341/assert/js/assert.js:28:13)
at assert (Disposable.ts:93:14)
at assertNotDisposable (Disposable.ts:83:48)
at dispose (PhetioObject.ts:828:10)
at dispose (Node.ts:6497:10)
at dispose (ComponentVectorNode.ts:124:10)
at call (Disposable.ts:50:21)
at dispose (VectorSetNode.ts:143:31)
at (TinyEmitter.ts:136:42)
at emit (Emitter.ts:61:21)
at emit (createObservableArray.ts:357:79)
at forEach (createObservableArray.ts:357:20)
at splice (arrayRemove.js:21:8)
at (createObservableArray.ts:391:52)
at remove (VectorCreatorPanelSlot.ts:168:30)
at finishCallback (Vector.ts:377:6)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (Animation.ts:321:25)
at (TinyEmitter.ts:122:18)
at emit (Sim.ts:413:16)
at apply (PhetioAction.ts:161:16)
at execute (Sim.ts:1017:30)
at stepSimulation (Sim.ts:1007:11)
at stepOneFrame (Sim.ts:982:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
at requestAnimationFrame (Sim.ts:972:11)
id: Sparky Playwright Firefox
Snapshot from 7/5/2023, 2:27:09 PM
```

**Comment by pixelzoom** [comment]
This bug was introduced in https://github.com/phetsims/axon/issues/436.  Fixed in the above commit.  I'll leave this open for a few CT cycles to be sure.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
