### ISSUE TITLE
CT issue with VectorLabelNode

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#54]
````
vector-addition : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/assert/js/assert.js:22:13)
    at VectorLabelNode.setCenter (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561599106252:2850:17)
    at VectorLabelNode.set center [as center] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561599106252:2856:32)
    at VectorComponentNode.updateLabelPositioning (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/VectorComponentNode.js?bust=1561599106252:240:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/BaseVectorNode.js?bust=1561599106252:84:16
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Multilink.js?bust=1561599106252:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/TinyEmitter.js?bust=1561599106252:59:55)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599106252:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599106252:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599106252:316:34)
id: Bayes Chrome
Approximately 6/26/2019, 8:41:06 PM
vector-addition : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas
Uncaught Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/assert/js/assert.js:22:13)
    at VectorLabelNode.setCenter (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561597825959:2850:17)
    at VectorLabelNode.set center [as center] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561597825959:2856:32)
    at VectorComponentNode.updateLabelPositioning (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/VectorComponentNode.js?bust=1561597825959:240:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/BaseVectorNode.js?bust=1561597825959:84:16
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Multilink.js?bust=1561597825959:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/TinyEmitter.js?bust=1561597825959:59:55)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561597825959:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561597825959:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561597825959:316:34)
id: Bayes Chrome
Approximately 6/26/2019, 8:41:06 PM
vector-addition : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/assert/js/assert.js:22:13)
    at VectorLabelNode.setCenter (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561599379415:2850:17)
    at VectorLabelNode.set center [as center] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/scenery/js/nodes/Node.js?bust=1561599379415:2856:32)
    at VectorComponentNode.updateLabelPositioning (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/VectorComponentNode.js?bust=1561599379415:240:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/vector-addition/js/common/view/BaseVectorNode.js?bust=1561599379415:84:16
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Multilink.js?bust=1561599379415:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/TinyEmitter.js?bust=1561599379415:59:55)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599379415:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599379415:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1561596066998/axon/js/Property.js?bust=1561599379415:316:34)
id: Bayes Chrome
Approximately 6/26/2019, 8:41:06 PM
```

**Comment by veillette** [comment]
This has to do with VectorLabelNode. I have been trying to reproduce it manually but to no avail.

In VectorComponentNode, we have  
```
 this.labelNode.center = modelViewTransform.modelToViewDelta( midPoint.plus( offset ) );
```
 My guess is that the labelNode is empty and it is trying to center something with zero  or null Bounds.

**Comment by brandonLi8** [comment]
I think its fixed with e87e3bac255ec99926124a7dc9d4058d190789fc

**Comment by brandonLi8** [comment]
Unable to reproduce, even after 20 min of fuzzing

**Comment by veillette** [comment]
CT is fine as well. Closing
